### ISSUE TITLE
node相关资料

### ISSUE THREAD

**Issue by Yunkou** [liziqiang/Clarion#1]
## node.js相关的中文文档及教程
1. node.js api中英文对照:
   http://docs.cnodejs.net/cman/ 
2. node.js入门中文版:
   http://nodebeginner.org/index-zh-cn.html 
3. express3.0中文API:
   http://expressjs.jser.us/
4. jade中文文档: 
   http://expressjs.jser.us/jade.html 
5. meteor中文文档:
   http://d0cs.meteor.com/ 
6. NodeJS 和 Socket.io 中文入门教程:
   http://t.cn/zOMwxCg 
7. Juicer 中文文档:
   http://juicer.name/docs/docs_zh_cn.html 
8. Mongoose 基本功能使用:
   http://t.cn/zOIKPeB
## 以下是一些blog教程系列:
1. 一起学node.js (荐):
   http://t.cn/zHxNXXt 
2. Node.js高级编程(荐):
   http://t.cn/zYmuqaH 
3. 深入浅出Node.js
   http://www.infoq.com/cn/articles/what-is-nodejs 
4. Node.js零起点开发:
    http://blog.csdn.net/kaosini/article/details/8084268 
5. node.js入门(共13篇)
   http://www.cnblogs.com/softlover/category/406516.html
6. snoopyxdy的博客(大量node及express api的解读及进阶内容):
   http://t.cn/a3hDsu
7. 用node.js写web框架系列:
   http://my.oschina.net/Jeky/blog?catalog=262655
8. Luics的node.js系列:
   http://t.cn/zjATQlf
9. 使用node.js建博客:
   http://witcheryne.iteye.com/blog/1172069

**Comment by liziqiang** [comment]
给力:-)
